info:
  contact: {}
  license: {}
paths:
  /api/users/create:
    post:
      summary: Create a new user
      tags:
      - users
  /api/users/deleteUser:
    delete:
      summary: Deletes a user using a user id
      tags:
      - users
  /api/users/getCurrentUser:
    get:
      summary: Attempts to get the currently logged in user using there session id.
      tags:
      - users
  /api/users/getUserById:
    get:
      summary: Attempts to get a existing user by id
      tags:
      - users
  /api/users/login:
    post:
      summary: Attempt to login using user details
      tags:
      - users
  /api/users/updateUserDetails:
    post:
      summary: Updates a users details
      tags:
      - users
